### ISSUE TITLE
Scalarm responsivness

### ISSUE THREAD

**Issue by grzanka** [Scalarm/scalarm#4]
I see very long lags in SCALARM UI:

 - verifying PLGRID credentials when adding computer power takes ~5s
 - the time between the moment I click "Add resources" and the moment the resource pops up with the status "Created" is around 30s

Is it normal and expected ? It it is very very annoying. See
https://www.youtube.com/watch?v=aaYf9a0XetE&feature=youtu.be

**Comment by dkrol** [comment]
The observed latency is not only related to verification of PLGrid credentials. Scalarm also retrieves information about computing grants on PLGrid, which requires access to PLGrid infrastructure. We will investigate if we can do something about it.

Regarding the time you see created the resources, it is related to the way we refresh UI. We use AJAX calls every 30 seconds. That's why you see such a delay.

**Comment by grzanka** [comment]
From an user perspective waiting for reaction longer that 3s for something that seems obvious is disqualifying the app.

**Comment by dkrol** [comment]
I agree that 3 seconds is a long time to wait. However, it obviously depends on things going in the background. We tried to do something about it. But there is still a lot of room for improvements.
